JavaScript 問題
taisuke11/JavaScriptQuestions pull request #1
Opened 2018-09-20 06:30 UTC by taisuke11

question1/index.html
question1/question1.js
上記の二つのファイルに関してはmasterブランチだと削除されていますが
お手数ですがdevelopのブランチを優先してください

2018-09-28 05:07 UTC, tkawa requested changes
はじめまして、ソニックガーデンの川村です。
ひととおり見ました。課題の文章がわかりづらいところもあったと思いますが、細かい配慮がいろんなところに見られたのが良いと思いました 👍 

全体の印象としては、変数名がわかりにくいものが多いです。その変数の意味を考えてつけるようにしましょう。
整数は `xxxValue` 文字列は `xxxString` 配列は `xxxArray` とつけていることが多いようですが、これは決してわかりやすいとはいえません。むしろ xxx の部分が大事ですので、これを略さず意味に応じてつけるのがわかりやすくするポイントです。

例えば課題2は「文字列に含まれる単語の数を、単語ごとに数える」ですから、「単語」を格納する変数は `word` 、その配列は `words` とするのがシンプルです。

2018-09-28 05:07 UTC, tkawa commented on question1/question1.js
> +const getNumber = Number (prompt ('数字を入力してください。'));
【細かい】
`getNumber` という名前は「値を得る関数」のように感じられます。
一般的に動詞で始まる名前は動作を表すことから関数・メソッドであることが多いです。
あえてていねいにするなら `enteredNumber` みたいな感じですが、そんなに複雑なプログラムでもないので `number` でも十分だと思います。

他の `getXxx` も同様。

2018-09-28 05:07 UTC, tkawa commented on question1/question1.js
> +for (const value of Array.from ({length: getNumber}, (v, k) => k + 1)) {
`{length: getNumber}, (v, k) => k + 1` がおしゃれな感じですが、ここでは普通に
```js
for (let i = 1; i <= getNumber; i++) {
```
のほうがわかりやすいと思います。

2018-09-28 05:07 UTC, tkawa commented on question1/question1.js
> +    resultStr += ', ';
【応用】
こういうメインの処理とは関係ないコードが入ってくるのが少し見にくいので、
`result` を String ではなく Array で保持して、最後に `join` するとすっきりしますよ。

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +getString = getString.replace (/\"/g, '');
なるほど。配慮ですね 😃

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +arrayOfString = getString.split (' ');
`arrayOfString` 自体をこの後変更していないので `const arrayOfString = getString.split(' ');` でOKです。
変数は最初に使用する直前で宣言して初期化するのがよいのですが、初期化する値は他の関数の返り値でもかまいません。
下の `hashArray` も同様。

【細かい】
また `arrayOfString` は「単語の配列」なので `arrayOfWord`、もっと単純に `words` でもいいと思います。

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +hashArray = {};
array という名前だけど配列じゃないのでは？

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +for (const arrayStr of arrayOfString) {
arrayStr も配列じゃないですよね。

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +      hashArray[arrayStr] = hashArray[arrayStr] + 1;
JavaScriptのオブジェクトは、こういうループを回して存在判定する必要がないというのが便利なところですので、活用しましょう。
```js
if (hashArray[arrayStr]) {
  hashArray[arrayStr]++; // 存在する場合
} else {
  hashArray[arrayStr] = 1; // 存在しない場合 (undefined)
}
```

2018-09-28 05:07 UTC, tkawa commented on question2/question2.js
> +// 統一するために文字列に変換する
なぜそうなるかわかりませんが、配慮ありがとうございます 😄

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +const intervalID = setInterval (function () {
`setInterval` は一定の時間間隔で繰り返すための関数です。
ここではアイコのとき繰り返したいので、使用するのは適切ではないです。
`while` などの普通のループに書き直しましょう。

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +    getValue = -1;
`Number` 関数は「空欄や全角スペースや半角スペースで変換すると0になってしまう」のですが、
`ParseInt` を使うと0にならず `NaN` になるので、ここの判定は不要になります。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/parseInt
```js
getValue = parseInt(getValue, 10); // 第2引数には10を指定しておくのがよい
```

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +  if (typeof zyankenHash[getValue] === 'undefined') {
単にこれで十分かな、と。（なぜこう書けるかわかりますか？）
```js
if (!zyankenHash[getValue]) {
```

また、この時点でこれより後の処理は実行したくないので `return` や `continue` で次のループに進んでしまいましょう。そうすると `else` がいらなくなります。

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +    computerValue = Math.floor (Math.random () * Math.floor (3));
`Math.floor (3)` はただの `3` と同じでは。

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +    // 故に、左を基準として2か-1の時は勝ち、同値はあいこ、それ以外は負けになる
コメントわかりやすいです 👍

2018-09-28 05:07 UTC, tkawa commented on question3/question3.js
> +    if (drawFlag === false) {
true/false との比較は冗長なので、単に `if (!drawFlag) {` でOKです。
（単純なループに書き直すと不要になるかもしれませんね）

2018-09-28 05:07 UTC, tkawa commented on question4/question4.js
> +let calProcessString = '（';
`（5+4+3+2+1 の結果）` は説明のためで、実際には出力しなくてよかったのですが、問題の記述があいまいですみません 🙇 
結果の数字だけを出力するということで `resultValue`, `calProcessString`, `sumValue` を使わないでシンプルな関数の再帰でやってみてください。

2018-09-28 05:07 UTC, tkawa commented on question5/question5.js
> +const iniArray = [20, 31, 42, 13, 5, 38];
【細かい】
`ini` は "initial" かな…？ あまり見かけない略し方ですね。
プロジェクトの方針にもよりますが、私はあまり略さなくてもいいと思います。

2018-09-28 05:07 UTC, tkawa commented on question5/question5.js
> +let averValue = 0;
【細かい】
`aver` も無理に略さず `average` で。

2018-09-28 05:07 UTC, tkawa commented on question5/question5.js
> +      for (const i of Array (ArraySize - count1 - 1).keys ()) {
ここのループは必要以上に複雑ですね。バブルソートなのに隣接要素以外の比較が行われているような……。
`sortBySmallArray[count1]` と `sortBySmallArray[count2]` の交換、というのがポイントなので、それに合うようにループさせましょう。
```js
for (let i = 0; i < ArraySize - 1; i++) {
  for (let j = 1; j < ArraySize - i - 1; j++) { // ループごとに末尾の要素が確定していく
    const count1 = j - 1;
    const count2 = j;
    // 比較して交換する
}
```

また、配列の添字のことは index というので、`index1`, `index2` としたほうがわかりやすいです。

2018-09-28 05:07 UTC, tkawa commented on question5/question5.js
> +  right = [];
不要な代入

2018-09-28 05:07 UTC, tkawa commented on question5/question5.js
> +    const count = i + 1;
このほうがわかりやすいです。
```js
for (let count = 1; count < seq.length; count++) {
```

2018-09-28 05:07 UTC, tkawa commented on question6/question6.js
> +const intervalID = setInterval (function () {
普通のループにしましょう。

2018-09-28 05:07 UTC, tkawa commented on question6/question6.js
> +const answerNumber = Math.floor (Math.random () * Math.floor (101));
`Math.floor (101)` は `101`

2018-09-28 05:07 UTC, tkawa commented on question6/question6.js
> +    console.log ('入力した数字：' + String (getNumber));
配慮良いですね 👍

2018-09-28 05:07 UTC, tkawa commented on question6/question6.js
> +      console.log (hintMessage);
短いので `correctFlag` を使わなくても直接書いてもいいかなと思いました。

2018-09-28 05:07 UTC, tkawa commented on question6/question6.js
> +    Math.round (getNumber) !== getNumber
【参考】
parseInt では小数が入力されたとき判別できませんが、そのような厳密な判別が必要なときは正規表現が使えます。
[より厳密な解析関数](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/parseInt#%E3%82%88%E3%82%8A%E5%8E%B3%E5%AF%86%E3%81%AA%E8%A7%A3%E6%9E%90%E9%96%A2%E6%95%B0)

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +baseArray = Array.apply (null, {length: 10}).map (Number.call, Number);
トリッキーすぎます 😓 
`[...Array(10).keys()]` ぐらいでどうでしょうか……。
ここは変わらないのでベタで `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` と書いてもかまいません。
また let ではなく const で。

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +function getAnsewerNumber (ansewerNubmerArray, selectNumberArray) {
【typo】
`ansewer` → `answer`
`Nubmer` → `Number`

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +    value => value !== selectNumberArray[indexNumber]
これを同時にするための splice というメソッドがありますよ。
```js
answerNumberArray.push(...selectNumberArray.splice(indexNumber, 1));
```
- [Array.prototype.splice() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +  return getAnsewerNumber (ansewerNubmerArray, selectNumberArray);
再帰を使うのは良いのですが、引数に `answerNumberArray` を与えるのはあまり良くないです。これは結果なので返り値で取得すべきものだからです。
なので、再帰を使わない形で書いたほうがスッキリするのではと思います。

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +    tempValue.indexOf ('　') !== -1
「空欄、文字列、小数点を含む数字、4桁でない数字はエラー」これも正規表現を使うとスッキリ書けますよ。

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +  // 同じ数字を二つ以上入れるのは戦略としてありだと思ったので
ありだと思います 👍

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +      for (const count2 of [0, 1, 2, 3]) {
こっちで `array0_4` を使っていないのはなぜ？
`forEach` と `for...of` の使い分けには理由があるでしょうか。

2018-09-28 05:07 UTC, tkawa commented on question7/question7.js
> +            hitCount += 1;
【好み】
`hitCount++;` でもOKです。

2018-10-01 14:21 UTC, taisuke11 commented on question3/question3.js
> +const intervalID = setInterval (function () {
初めにwhileの方法も試したのですが
少なくとも私が考えた方法ですと、ファイルを初めて読み込んだ際に
ログが表示されませんでした。
setInterval を使わないとログに表示されなかったので
此方を採用しました。

この問題には事前に気が付いていたのですが、
この旨をコメントに書いていなくて申し訳ございません。

恐縮ですが、何かいい方法はありますでしょうか？

以下が検証したコードです。
```
'use strict';
let value = 0;
let count = 0;
do {
  value = Number (prompt ('数字を入力してください。1の時にループを抜けます'));
  count++;
  console.log ('ループ' + String (count) + '回目');
} while (value != 1);
```

2018-10-01 14:22 UTC, taisuke11 commented on question6/question6.js
> +const intervalID = setInterval (function () {
初めにwhileの方法も試したのですが
少なくとも私が考えた方法ですと、ファイルを初めて読み込んだ際に
ログが表示されませんでした。
setInterval を使わないとログに表示されなかったので
此方を採用しました。

この問題には事前に気が付いていたのですが、
この旨をコメントに書いていなくて申し訳ございません。

恐縮ですが、何かいい方法はありますでしょうか？

以下が検証したコードです。
```
'use strict';
let value = 0;
let count = 0;
do {
  value = Number (prompt ('数字を入力してください。1の時にループを抜けます'));
  count++;
  console.log ('ループ' + String (count) + '回目');
} while (value != 1);
```

2018-10-01 14:32 UTC, taisuke11 commented
お待たせしました。ソニックガーデンの川村様。
指摘された内容を修正しました。

先走って修正してしまい恐縮ですが
確認したい点が二点あります。

question3とquestion6のsetIntervalの件なのですが
whileだと初回にファイルを読み込んだ際に
ログに表示されないのでsetIntervalを使いました。

下記は二つとも同様の内容ですが、もう少し詳細の内容を各自コメントに返信したので
確認をお願いします。

[question3.jsのsetIntervalの件](https://github.com/taisuke11/JavaScriptQuestions/pull/1#discussion_r221627154)
[question6.jsのsetIntervalの件](https://github.com/taisuke11/JavaScriptQuestions/pull/1#discussion_r221627451)

2018-10-02 01:26 UTC, tkawa commented on question3/question3.js
> +const intervalID = setInterval (function () {
検証コードありがとうございます。
私の手元のChrome(69)ではちゃんと表示されているように見えるのですが、
「ファイルを初めて読み込んだ際にログが表示されませんでした」をもう少し詳しく説明してもらえますか？
![cb158a301c40d5aa4cced3e8344c076f](https://user-images.githubusercontent.com/562433/46324246-83b05700-c62d-11e8-8b4e-63a18ab8c329.gif)

2018-10-02 03:31 UTC, taisuke11 commented on question3/question3.js
> +const intervalID = setInterval (function () {
動作手順は以下の通りになります。
１．javascrptを読み込むhtmlファイルを開きます
２．F12でデバックコンソールを開きます
３．数字を入力します。
４．表示されないので1を入力します。
５．コンソールログが表示されます
この後にF5で更新すると、入力後すぐにログが表示されるようになります。

現在使用しているChoromeはバージョン: 69.0.3497.100（Official Build）です。

![3](https://user-images.githubusercontent.com/41357606/46327826-b4e55300-c63e-11e8-91b5-bea139752ad1.gif)

2018-10-02 04:24 UTC, tkawa commented on question3/question3.js
> +const intervalID = setInterval (function () {
なるほど、ありがとうございます。
想像ですが、F12でコンソールを開いたときにコード上の `console` とつなげるような処理を内部で行うのだと思います。そのときちょうど `prompt` でスクリプトの実行をブロックしているため、その処理が「待ち」の状態になっているのではないかと。引き続き while ループでもブロックされ続け、実行が終了したときに初めてその処理が行われ、コンソールログが画面に表示される。
`setInterval` の場合は、次回の実行を予約したような状態になり、いったんスクリプトの実行が終了します。そうすると `console` とつなげる処理が動くようになる。

ということで、その挙動はプログラムの不具合ではないです。
コンソールはHTMLを読み込んでJavaScriptが動作する前に開いておきましょう。
このあたりのことは少し高度ですが「シングルスレッド」「イベントループ」あたりで調べるとわかってきます。
（実はJavaScriptにおいては `while` のような単純なループよりも `setTimeout` やイベントを使ったコードのほうが効率がよくなる、ということがいえますが、使い方を正しく理解する必要があることと、今回の課題の趣旨から外れているので、まずは素直なループで書くことを優先しましょう）
- [「for やめろ」またはイベントループと nextTick() - Block Rockin’ Codes](http://jxck.hatenablog.com/entry/for-with-eventloop)
- [UIスレッドとwindow.alert – 閉口 – Medium](https://medium.com/@yn2011/ui%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89%E3%81%A8window-alert-c3aafa8c8f62)

2018-10-02 13:46 UTC, taisuke11 commented on question3/question3.js
> +const intervalID = setInterval (function () {
返信ありがとうございます。コンソールの件はこちらでも動作したのを確認できました。
さきほど修正したソースコードを上げましたので
お手数をおかけしますが確認をお願いします。

2018-10-03 01:48 UTC, tkawa requested changes
かなりよくなりました。
question7にもループがありましたね。コメント忘れてましたがそちらも修正お願いします。

2018-10-03 01:48 UTC, tkawa commented on question3/question3.js
>  //Consoleに表示されない問題があった為です。
このコメントも消しておきましょう。

2018-10-03 01:48 UTC, tkawa commented on question6/question6.js
> +      keepLoopFlag = false;
`keepLoopFlag` というのはあまり意味のない名前なので、できるならもっと直接的な名前にしたいところ、と思ったのですがあまり良い名前が思いつかないですね 💦 
`success = true` とか。。

ただこの場合は、フラグを使わず単純に `break` してしまえば十分わかりやすいと思います。

2018-10-03 01:48 UTC, tkawa commented on question1/question1.js
> +console.log (result.join ([', ']));
`join` の引数は文字列です。`toString()` が呼ばれるのでたまたま正しく動きますが、わかりにくいので文字列にしましょう。

メソッドの仕様を調べるときはどうしていますか？ MDNを調べるのが確実な方法だと思います。（翻訳されていない項目もあったりしますが）
- [Array.prototype.join() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/join)

2018-10-03 01:48 UTC, tkawa commented on question2/question2.js
> +const arrayOfWords = word.split (' ');
なるほど `arrayOfWords` 😃

2018-10-03 01:48 UTC, tkawa commented on question4/question4.js
> +  return calSumValue (value - 1) + value;
シンプルになりました 👍

2018-10-03 01:48 UTC, tkawa commented on question5/question5.js
> +let index1 = 1;
不要です。

2018-10-03 01:48 UTC, tkawa commented on question5/question5.js
> +sortBySmallArray = initialArray;
代入してますが、これはコピーではないので `initialArray` の内容も変わってしまうと思います。
バブルソートの後、クイックソートをする前に `initialArray` の内容を見てみてください。ソートされているはず。

配列をコピーするにはいくつか方法がありますが、`concat()` が楽でしょうね。
- [Array.prototype.concat() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

2018-10-03 01:48 UTC, tkawa commented on question6/question6.js
> +//その為、今回は敢えてsetIntervalを採用した。
このコメントも消しておきましょう。

2018-10-03 01:48 UTC, tkawa commented on question7/question7.js
> +const intervalID = setInterval (function () {
ここも普通のループにしましょう。

2018-10-03 01:48 UTC, tkawa commented on question7/question7.js
> +let answerNumberArray = [initialRandomNumber];
ここでやってることは下のループ内でやってることと同じなので、空で始めてループの回数を1回増やすだけでいいと思います。

2018-10-03 01:48 UTC, tkawa commented on question6/question6.js
> +  if (/^(\-|\+)?([0-9]+)$/.test (value)) return Number (value);
符号の入力までOKにするのはちょっと変です。
`/^\d+$/` というのがシンプルですね。

2018-10-03 01:48 UTC, tkawa commented on question7/question7.js
> +    if (/^(\+)?([0-9]{4})$/.test (value)) return Number (value);
こちらも符号の入力までOKにするのはちょっと変です。
`/^\d{4}$/` がシンプル。

2018-10-03 06:56 UTC, taisuke11 commented on question1/question1.js
> +console.log (result.join ([', ']));
JavaScriptのメソッドを調べる際に一度はMDNに目を通すようにしていて
実際今回はそのページを見たのですが、内容をよく読まないまま
該当のページをコピーして貼り付けて小手先の修正で通してしまったため、
今回のようになりました。
以後気を付けます:droplet:

2018-10-03 07:00 UTC, taisuke11 commented
纏めてで恐縮ですが、レビューありがとうございます。
ご指摘のあった、question1、question3、question5、question6、question7
の内容を修正しました。
お手数をおかけしますが、確認をお願いします。

2018-10-04 01:42 UTC, tkawa approved these changes
さらによくなったと思います  👍 

今回いくつかの課題では関数を作りました。今回の課題は短いですが、これから長いコードになってくると重複する部分を関数にして再利用するということをよく行います。重複している部分はないかな、ということを意識してコードを書いていくようにしましょう。
conflictを解消してマージできたら完了です。おつかれさまでした！

2018-10-05 02:09 UTC, merged

2018-10-05 02:11 UTC, taisuke11 commented
conflictを解消してマージしました。
色々丁寧にご指摘していただき
本当にありがとうございました。
至らぬ点が自覚できましたし、とても耳に入りやすかったです。